// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTag(arg1) {
  return window['go']['main']['App']['AddTag'](arg1);
}

export function AddTodo(arg1) {
  return window['go']['main']['App']['AddTodo'](arg1);
}

export function DelTag(arg1) {
  return window['go']['main']['App']['DelTag'](arg1);
}

export function ListTag() {
  return window['go']['main']['App']['ListTag']();
}

export function ListTodo(arg1) {
  return window['go']['main']['App']['ListTodo'](arg1);
}

export function MarkTodo(arg1) {
  return window['go']['main']['App']['MarkTodo'](arg1);
}

export function RemoveTodo(arg1) {
  return window['go']['main']['App']['RemoveTodo'](arg1);
}

export function UpdateTag(arg1) {
  return window['go']['main']['App']['UpdateTag'](arg1);
}

export function UpdateTodo(arg1) {
  return window['go']['main']['App']['UpdateTodo'](arg1);
}
