// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTag(arg1:string):Promise<string>;

export function AddTodo(arg1:string):Promise<string>;

export function DelTag(arg1:string):Promise<string>;

export function ListTag():Promise<string>;

export function ListTodo(arg1:string):Promise<string>;

export function MarkTodo(arg1:string):Promise<string>;

export function RemoveTodo(arg1:string):Promise<string>;

export function UpdateTag(arg1:string):Promise<string>;

export function UpdateTodo(arg1:string):Promise<string>;
